Resources:
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body: ${file(resources/Space-Bandits-spacebandit-1.0.0-swagger.yaml)}
      Name : "Neural Bandit API"
      Parameters:
        endpointConfigurationTypes: REGIONAL
